@startuml
skinparam style strictuml
skinparam BoxPadding 10
skinparam ParticipantPadding 10

actor User
participant "CodeFormattingService" as Service
participant "DynamicGrammar" as Grammar
participant "LexerInterpreter" as Lexer
participant "CommonTokenStream" as TokenStream
participant "ParserInterpreter" as Parser
participant "TokenStreamRewriter" as Rewriter
participant "ParseTreeWalker" as Walker
participant "FormatterListener" as Listener

User -> Service: formatCode(grammar, code)
activate Service

Service -> Grammar: createLexerInterpreter(input)
activate Grammar
Grammar --> Service: lexerInterpreter
deactivate Grammar

Service -> Lexer: (tokenize)
activate Lexer
Lexer --> TokenStream: create
deactivate Lexer

Service -> TokenStream: fill()
activate TokenStream
TokenStream --> Service: TokenStream (filled)
deactivate TokenStream

Service -> Grammar: createParserInterpreter(tokenStream)
activate Grammar
Grammar --> Service: parserInterpreter
deactivate Grammar

Service -> Parser: parse(startRuleIndex)
activate Parser
Parser --> Service: ParseTree
deactivate Parser

Service -> Rewriter: create(tokenStream)
activate Rewriter
Rewriter --> Service: TokenStreamRewriter
deactivate Rewriter

Service -> Walker: walk(FormatterListener, ParseTree)
activate Walker

loop For each TerminalNode
    Walker -> Listener: visitTerminal(node)
    activate Listener

    Listener -> Listener: check rules ({, }, ;, etc.)

    Listener -> TokenStream: getHiddenTokensToLeft/Right(tokenIndex)
    activate TokenStream
    TokenStream --> Listener: hiddenTokens (whitespace)
    deactivate TokenStream

    alt Needs formatting adjustment
        Listener -> Rewriter: insertBefore/insertAfter/replace(token, expectedWhitespace)
        activate Rewriter
        Rewriter --> Listener: queued instruction
        deactivate Rewriter
    end

    Listener --> Walker: (continue)
    deactivate Listener
end

Walker --> Service: (walk complete)
deactivate Walker

Service -> Rewriter: getText()
activate Rewriter
Rewriter --> Service: formattedCode
deactivate Rewriter

Service --> User: formattedCode
deactivate Service
@enduml
